/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.germer.starit;

import org.hamcrest.MatcherAssert;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

class MainTest {


    private ByteArrayOutputStream stdOutput;
    private ByteArrayOutputStream stdError;

    @BeforeEach
    public void setupEach() {
        stdOutput = new ByteArrayOutputStream();
        stdError = new ByteArrayOutputStream();
        System.setOut(new PrintStream(stdOutput));
        System.setErr(new PrintStream(stdError));
    }

    @Test
    @DisplayName("Sample output with original provided code")
    void originalDirtyAppOutput() {
        Main.main(new String[]{});

        assertThat(getStdOutAsString(), equalToCompressingWhiteSpace(
                "Highest rating category: Colors; thing: blue; rating: 10\n" +
                        "Category with highest sum: Dogs; sum was 29"
        ));
        assertThat(getStdErrAsString(), is(emptyString()));
    }


    private String getStdOutAsString() {
        return stdOutput.toString();
    }

    private String getStdErrAsString() {
        return stdError.toString();
    }
}
